/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-fastsrc
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_FASTSRC_API_H
#define INCLUDED_FASTSRC_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_fastsrc_EXPORTS
#define FASTSRC_API __GR_ATTR_EXPORT
#else
#define FASTSRC_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_FASTSRC_API_H */
